import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Astronaut Tee',
    description: 'A comfortable and stylish t-shirt featuring a unique astronaut design. Made from 100% premium cotton for a soft feel.',
    price: 29.99,
    imageUrl: 'https://placehold.co/600x600.png',
    data_ai_hint: 'tshirt astronaut',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Apparel',
    stock: 50,
  },
  {
    id: '2',
    name: 'Galaxy Hoodie',
    description: 'Stay warm and stylish with our galaxy-themed hoodie. Features a vibrant all-over print and a soft fleece interior.',
    price: 59.99,
    imageUrl: 'https://placehold.co/600x600.png',
    data_ai_hint: 'hoodie galaxy',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Apparel',
    stock: 30,
  },
  {
    id: '3',
    name: 'Smart Watch X1',
    description: 'The latest in wearable technology. Track your fitness, receive notifications, and customize your watch face. Long-lasting battery life.',
    price: 249.99,
    imageUrl: 'https://placehold.co/600x600.png',
    data_ai_hint: 'smart watch',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Electronics',
    stock: 20,
  },
  {
    id: '4',
    name: 'Wireless Earbuds Pro',
    description: 'Immerse yourself in high-fidelity sound with our Pro series wireless earbuds. Active noise cancellation and a comfortable, secure fit.',
    price: 179.99,
    imageUrl: 'https://placehold.co/600x600.png',
    data_ai_hint: 'wireless earbuds',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Electronics',
    stock: 45,
  },
  {
    id: '5',
    name: 'Modern Desk Lamp',
    description: 'A sleek and minimalist LED desk lamp. Adjustable brightness and color temperature to suit your workspace. Energy efficient.',
    price: 79.99,
    imageUrl: 'https://placehold.co/600x600.png',
    data_ai_hint: 'desk lamp',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Home Goods',
    stock: 25,
  },
  {
    id: '6',
    name: 'Smart Speaker Mini',
    description: 'Your voice-activated assistant. Play music, set alarms, and control your smart home devices with this compact and powerful speaker.',
    price: 49.99,
    imageUrl: 'https://placehold.co/600x600.png',
    data_ai_hint: 'smart speaker',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Electronics',
    stock: 60,
  },
  {
    id: '7',
    name: 'Cosmic Coffee Mug',
    description: 'Start your day with a cup of coffee in this beautiful ceramic mug featuring a stunning cosmic design. Dishwasher and microwave safe.',
    price: 19.99,
    imageUrl: 'https://placehold.co/600x600.png',
    data_ai_hint: 'coffee mug',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Home Goods',
    stock: 100,
  },
  {
    id: '8',
    name: 'Rocketship Backpack',
    description: 'A fun and durable backpack perfect for school or travel. Features multiple compartments and a cool rocketship design.',
    price: 45.99,
    imageUrl: 'https://placehold.co/600x600.png',
    data_ai_hint: 'backpack space',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    category: 'Accessories',
    stock: 40,
  },
];
