
import type { Product } from './types';

export const products: Omit<Product, 'id'>[] = [
    {
      name: 'Vans Old Skool',
      description: 'Classic skate shoe with iconic side stripe, durable canvas and suede uppers, and signature rubber waffle outsoles.',
      price: 4999,
      imageUrl: 'https://placehold.co/600x600.png',
      images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
      category: 'Skate Shoes',
      stock: 50,
      data_ai_hint: 'skate shoe',
      sizes: ["7", "8", "9", "10", "11"]
    },
    {
      name: 'Santa Cruz Deck',
      description: 'The classic Santa Cruz logo on a high-quality 7-ply maple deck. Perfect for street and park skating.',
      price: 3499,
      imageUrl: 'https://placehold.co/600x600.png',
      images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
      category: 'Decks',
      stock: 30,
      data_ai_hint: 'skateboard deck',
    },
    {
      name: 'Independent Trucks',
      description: 'Durable and high-performance trucks for a smooth ride. Stage 11 standard profile.',
      price: 2499,
      imageUrl: 'https://placehold.co/600x600.png',
      images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
      category: 'Trucks',
      stock: 40,
      data_ai_hint: 'skateboard trucks',
    },
    {
      name: 'Spitfire Wheels',
      description: 'Formula Four classic shape wheels, known for their speed and control. 54mm 99a durometer.',
      price: 2999,
      imageUrl: 'https://placehold.co/600x600.png',
      images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
      category: 'Wheels',
      stock: 60,
      data_ai_hint: 'skateboard wheels',
    },
    {
      name: 'Bones Reds Bearings',
      description: 'The industry standard bearings. High speed, durable, and easy to clean.',
      price: 1499,
      imageUrl: 'https://placehold.co/600x600.png',
      images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
      category: 'Bearings',
      stock: 100,
      data_ai_hint: 'skateboard bearings',
    },
    {
      name: 'Element T-Shirt',
      description: 'Classic fit t-shirt with a small Element logo on the chest. Made from 100% organic cotton.',
      price: 1999,
      imageUrl: 'https://placehold.co/600x600.png',
      images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
      category: 'Apparel',
      stock: 75,
      data_ai_hint: 'skate shirt',
      sizes: ["S", "M", "L", "XL"]
    },
    {
      name: 'Thrasher Hoodie',
      description: 'The iconic Thrasher Magazine flame logo hoodie. A must-have for any skater.',
      price: 5999,
      imageUrl: 'https://placehold.co/600x600.png',
      images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
      category: 'Apparel',
      stock: 25,
      data_ai_hint: 'skate hoodie',
      sizes: ["S", "M", "L", "XL"]
    },
    {
      name: 'Pro-Tec Helmet',
      description: 'Certified classic skate helmet. High-impact ABS shell with EPS liner for maximum protection.',
      price: 3999,
      imageUrl: 'https://placehold.co/600x600.png',
      images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
      category: 'Safety Gear',
      stock: 40,
      data_ai_hint: 'skate helmet',
      sizes: ["S", "M", "L"]
    },
     {
      name: 'Nike SB Dunk Low',
      description: 'A streetwear and skate icon, the Dunk Low features a padded collar and puffy tongue for comfort and support.',
      price: 8999,
      imageUrl: 'https://placehold.co/600x600.png',
      images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
      category: 'Skate Shoes',
      stock: 15,
      data_ai_hint: 'skate shoe nike',
      sizes: ["8", "9", "9.5", "10", "11"]
    },
    {
      name: 'Creature Logo Deck',
      description: 'A gnarly deck for a gnarly skater. 7-ply North American Maple pressed individually using epoxy.',
      price: 3799,
      imageUrl: 'https://placehold.co/600x600.png',
      images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
      category: 'Decks',
      stock: 22,
      data_ai_hint: 'skateboard deck green',
    },
    {
      name: 'OJ Super Juice Wheels',
      description: 'Soft and cruisy wheels perfect for filming or just rolling around town. 60mm 78a durometer.',
      price: 2799,
      imageUrl: 'https://placehold.co/600x600.png',
      images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
      category: 'Wheels',
      stock: 55,
      data_ai_hint: 'skateboard wheels orange',
    },
    {
      name: 'Dickies Skate Pants',
      description: 'Durable and comfortable work pants that have become a staple in skateboarding. Relaxed fit.',
      price: 4499,
      imageUrl: 'https://placehold.co/600x600.png',
      images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
      category: 'Apparel',
      stock: 35,
      data_ai_hint: 'skate pants',
      sizes: ["30x32", "32x32", "34x32", "36x34"]
    },
];

export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];
